[package]
name = "the-struggle"
version = "2.0.0"
authors = ["Joseph Lai"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.11"
clap = "2.33.1"
csv = "1.1.3"
prettytable-rs = "^0.8"
regex = "1.3.9"
serde = { version = "1.0.111", features = ["derive"] }
structopt = "0.3.14"
