[package]
name = "ts"
version = "2.0.1"
authors = ["Joseph Lai <jlai24142@gmail.com>"]
edition = "2018"
description = "A command-line tool for tracking your job applications"
homepage = "https://github.com/JosephLai241/The-Struggle"
license = "MIT"
readme = "README.md"
repository = "https://github.com/JosephLai241/The-Struggle"
categories = ["command-line-utilities"]
keywords = ["cli", "command-line tool", "csv", "job application", "tracking"]

[[bin]]
name = "ts"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.11"
clap = "2.33.1"
csv = "1.1.3"
prettytable-rs = "^0.8"
regex = "1.3.9"
serde = { version = "1.0.111", features = ["derive"] }
structopt = "0.3.14"

[dev-dependencies]
assert_cmd = "1.0.1"
