[display]
match_color = "red"
max_column_width = 45

[presets]
titles = ["Software Engineer"]

[presets.status_mappings]
hired = "green"
in-progress = "yellow"
offer-received = "cyan"
pending = "blue"
rejected = "red"
