[chatgpt]
api-key = "<CHATGPT_API_KEY_HERE>"

[display]
match-color = "red"
max-column-width = 45

[display.chart]
aspect-ratio = 3
radius = 9

[presets]
titles = ["Software Engineer"]

[presets.status_mappings]
hired = "green"
in-progress = "yellow"
offer-received = "cyan"
pending = "blue"
rejected = "red"
